# Generated by Django 3.2.6 on 2021-08-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswebAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
