# Generated by Django 3.2.6 on 2021-08-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswebAPI', '0002_auto_20210824_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('AA', 'Action and Adventure'), ('CL', 'Classics'), ('CM', 'Comic Book'), ('DM', 'Detective and Mystery'), ('FT', 'Fantasy')], default='CL', max_length=2),
        ),
    ]
