# Generated by Django 3.2.6 on 2021-08-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswebAPI', '0003_auto_20210824_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
