# Generated by Django 3.2.6 on 2021-08-24 22:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookswebAPI', '0004_alter_book_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added',
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.DateField(default=datetime.datetime(2021, 8, 24, 22, 35, 19, 707497, tzinfo=utc), max_length=20),
        ),
    ]
