# Generated by Django 3.2.6 on 2021-08-24 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookswebAPI', '0005_auto_20210824_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 24, 22, 54, 8, 110918, tzinfo=utc), max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
